apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: database-container
<<<<<<< HEAD
          image: 673896343304.dkr.ecr.us-east-1.amazonaws.com/project-mysql:v1.0
=======
          image: 508327803984.dkr.ecr.us-east-1.amazonaws.com/final:mydb-v1.0
>>>>>>> a78a424 (add imagepull secret)
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: final-secret 
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: my-pvc 
