apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: final
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 1Gi