apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: final
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVcyWDQ0T1FNQktEU082NTI=
  AWS_SECRET_ACCESS_KEY: NUIvSlc5OHhZeWxlMHNlMkFQL2ZEUWQ0c00waDhqMlpkSVlXK2l3RQ==

