apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: final
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      serviceAccountName: clo835
initContainers:
        - name: fetch-image
          image: appropriate/curl
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Fetching background image...";
              curl -o /usr/src/app/static/background.jpg -L $(cat /etc/config/BACKGROUND_IMAGE);
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: app-static
              mountPath: /usr/src/app/static
      containers:
        - name: application-container
          image: 469755524120.dkr.ecr.us-east-1.amazonaws.com/assigment-dev-app:v2
          imagePullPolicy: Always
      containers:
        - name: application-container
          image: 469755524120.dkr.ecr.us-east-1.amazonaws.com/assigment-dev-app:v2
          imagePullPolicy: Always
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DBHOST
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DBUSER
            - name: DBPORT
              value: "3306"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          envFrom:
            - configMapRef:
                name: group4
          ports:
            - containerPort: 81
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.5"
      imagePullSecrets:
        - name: project-secret

