apiVersion: v1
kind: Pod
metadata:
  name: api-test-pod
  namespace: final
spec:
  serviceAccountName: clo835
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["sh", "-c", "sleep 3600"]

